/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vegetable;

import java.awt.Color;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import oracle.jdbc.OraclePreparedStatement;
import oracle.jdbc.OracleResultSet;
import oracle.jdbc.OracleStatement;


/**
 *
 * @author heartless
 */
public class frmTransport extends javax.swing.JFrame {
    Connection con=null;
    OraclePreparedStatement pst=null;
     OracleStatement smt=null;
       OracleResultSet rs=null;

    /**
     * Creates new form frmTransport
     */
    public frmTransport() {
        initComponents();
         getTransportId();
         showDate();
         showTime();
    
         
       
         
         
          String str ="select * from VEGETABLE";
        try {
              con=ConnectDB.condb();
              smt=(OracleStatement)con.createStatement();
            rs=(OracleResultSet)smt.executeQuery("select * from VEGETABLE");
            while(rs.next())
            {
                
            cmbPro1.addItem(rs.getString(2));
             cmbPro2.addItem(rs.getString(2));
              cmbPro3.addItem(rs.getString(2));
            }
        }
        catch (Exception e)
                {
                }
    }
      void showDate()
         {
             Date d=new Date();
             SimpleDateFormat s=new SimpleDateFormat("dd-MM-YYYY");
             lblDate.setText(s.format(d));
             
             
         }
         void showTime()
         {
             new Timer(0,new ActionListener()
             {
                 @Override
                 public void actionPerformed(ActionEvent ae){
                     Date d=new Date();
                     SimpleDateFormat s=new SimpleDateFormat("hh:mm:ss");
                     lblTime.setText(s.format(d));
                 }
                         
             }).start();
             
         }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtVid = new javax.swing.JTextField();
        txtVtype = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtVno = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtDriid = new javax.swing.JTextField();
        txtDriname = new javax.swing.JTextField();
        txtDricont = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cmbPro3 = new javax.swing.JComboBox<>();
        cmbPro1 = new javax.swing.JComboBox<>();
        cmbPro2 = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtTotdis = new javax.swing.JTextField();
        txtRto = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtRfrom = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtDname = new javax.swing.JTextField();
        txtDcont = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(500, 150, 0, 0));
        setForeground(java.awt.Color.white);
        setResizable(false);
        setSize(new java.awt.Dimension(700, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 255), 3));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(255, 208, 217));
        jLabel5.setFont(new java.awt.Font("Algerian", 0, 24)); // NOI18N
        jLabel5.setText("Vegetable Transport System");
        jLabel5.setOpaque(true);
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        jLabel10.setBackground(new java.awt.Color(255, 208, 217));
        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel10.setText("Transport Details");
        jLabel10.setOpaque(true);
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 190, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon("D:\\vegetable transport project\\photos\\potato onion tomato.jpg")); // NOI18N
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-240, 0, 840, 100));
        jPanel6.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, -1, -1));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 100));

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(192, 217, 218));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vehical Detail", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Vehical Type-");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, -1, 20));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Vehical Id-");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 20));

        txtVid.setBackground(new java.awt.Color(255, 254, 240));
        txtVid.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtVid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtVidKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtVidKeyReleased(evt);
            }
        });
        jPanel1.add(txtVid, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 70, -1));

        txtVtype.setBackground(new java.awt.Color(255, 254, 240));
        txtVtype.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(txtVtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 120, -1));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel18.setText("Vehical No-");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, 20));

        txtVno.setBackground(new java.awt.Color(255, 254, 240));
        txtVno.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtVno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtVnoKeyReleased(evt);
            }
        });
        jPanel1.add(txtVno, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 120, -1));

        jPanel7.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 70));

        jPanel2.setBackground(new java.awt.Color(192, 217, 218));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Driver Detail", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Contact No");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, 20));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Id");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Name");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 40, -1));

        txtDriid.setBackground(new java.awt.Color(255, 254, 240));
        txtDriid.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtDriid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDriidKeyPressed(evt);
            }
        });
        jPanel2.add(txtDriid, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 80, -1));

        txtDriname.setBackground(new java.awt.Color(255, 254, 240));
        txtDriname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel2.add(txtDriname, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 190, -1));

        txtDricont.setBackground(new java.awt.Color(255, 254, 240));
        txtDricont.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtDricont.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDricontKeyPressed(evt);
            }
        });
        jPanel2.add(txtDricont, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 190, -1));
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, -1, -1));
        jPanel2.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 80, 20));
        jPanel2.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 70, 20));

        jPanel7.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 600, 80));

        jPanel3.setBackground(new java.awt.Color(192, 217, 218));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Product Detail", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Product Name");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Product Name");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Product Name");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        cmbPro3.setBackground(new java.awt.Color(255, 254, 240));
        cmbPro3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel3.add(cmbPro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 180, -1));

        cmbPro1.setBackground(new java.awt.Color(255, 254, 240));
        cmbPro1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel3.add(cmbPro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 180, -1));

        cmbPro2.setBackground(new java.awt.Color(255, 254, 240));
        cmbPro2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel3.add(cmbPro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 180, -1));

        jPanel7.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 600, 110));

        jPanel4.setBackground(new java.awt.Color(192, 217, 218));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Route Detail", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12))); // NOI18N
        jPanel4.setForeground(new java.awt.Color(204, 204, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("To");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setText("Total Distance");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        txtTotdis.setBackground(new java.awt.Color(255, 254, 240));
        txtTotdis.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel4.add(txtTotdis, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 100, -1));

        txtRto.setBackground(new java.awt.Color(255, 254, 240));
        txtRto.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel4.add(txtRto, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 110, -1));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setText("From");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 40, -1));

        txtRfrom.setBackground(new java.awt.Color(255, 254, 240));
        txtRfrom.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel4.add(txtRfrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 110, -1));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setText("KM");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, 20));

        jPanel7.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 600, 90));

        jPanel8.setBackground(new java.awt.Color(192, 217, 218));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Shipping Detail", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12))); // NOI18N
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setText("Distributor Name");
        jPanel8.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 120, -1));

        txtDname.setBackground(new java.awt.Color(255, 254, 240));
        txtDname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel8.add(txtDname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 190, -1));

        txtDcont.setBackground(new java.awt.Color(255, 254, 240));
        txtDcont.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtDcont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDcontActionPerformed(evt);
            }
        });
        txtDcont.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDcontKeyPressed(evt);
            }
        });
        jPanel8.add(txtDcont, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 190, -1));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel17.setText("Contact");
        jPanel8.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 60, 20));

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 600, 60));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSave.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon("D:\\vegetable transport project\\ICON\\save-png-hinew.jpg")); // NOI18N
        btnSave.setOpaque(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel5.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 80, 30));

        btnUpdate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon("D:\\vegetable transport project\\ICON\\update-png-hinew.jpg")); // NOI18N
        btnUpdate.setOpaque(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel5.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 80, 30));

        btnDelete.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon("D:\\vegetable transport project\\ICON\\delete-png-hinew.jpg")); // NOI18N
        btnDelete.setOpaque(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel5.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 80, 30));

        btnClear.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon("D:\\vegetable transport project\\ICON\\clear-png-hinew.jpg")); // NOI18N
        btnClear.setOpaque(false);
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel5.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 80, 30));

        btnExit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnExit.setIcon(new javax.swing.ImageIcon("D:\\vegetable transport project\\ICON\\.jpg")); // NOI18N
        btnExit.setOpaque(false);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel5.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 70, 30));

        jLabel19.setIcon(new javax.swing.ImageIcon("D:\\vegetable transport project\\photos\\owner.jpg")); // NOI18N
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 50));

        jPanel7.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 600, 50));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 600, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDcontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDcontActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDcontActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        
        con=ConnectDB.condb();
        try
        {
            pst=(OraclePreparedStatement)con.prepareStatement("UPDATE TRANSPORT SET V_NO=?,V_TYPE=?,DRI_ID=?,DRI_NAME=?,DRI_CONT=?,PRO_1=?,PRO_2=?,PRO_3=?,R_FROM=?,R_TO=?,TOT_DIS=?,D_NAME=?,D_CONT where V_NO=" +txtVid.getText());
           
             pst.setInt(1, Integer.parseInt(txtVid.getText()+""));
             pst.setString(2,txtVno.getText()+"");
             pst.setString(3,txtVtype.getText()+"");
            pst.setInt(4, Integer.parseInt(txtDriid.getText()+""));
            pst.setString(5,txtDriname.getText()+"");
            pst.setString(6,txtDricont.getText()+"");
            pst.setString(7,cmbPro1.getSelectedItem()+"");
            pst.setString(8,cmbPro2.getSelectedItem()+"");
            pst.setString(9,cmbPro3.getSelectedItem()+"");
            pst.setString(10,txtRfrom.getText()+"");
            pst.setString(11,txtRto.getText()+"");
            pst.setString(12,txtTotdis.getText()+"");
            pst.setString(13,txtDname.getText()+"");
            pst.setString(14,txtDcont.getText()+"");
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Updated...");
            pst.close();
            
        }
        catch(Exception e)
        {
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        
         con=ConnectDB.condb();

        try
        {
            pst=(OraclePreparedStatement)con.prepareStatement("Delete from TRANSPORT where V_NO=?");
            pst.setInt(1,Integer.parseInt(txtVid.getText()+""));
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Deleted...");
            clearAllFields();
      
        }
        catch(Exception e)
        {
        }
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        
         txtVtype.setText("");
        txtVid.setText("");
        txtDriid.setText("");
        txtDriname.setText("");
         txtDricont.setText("");
        txtRfrom.setText("");
        txtRto.setText("");
        txtTotdis.setText("");
         txtDname.setText("");
        txtDcont.setText("");
       
        
    }//GEN-LAST:event_btnClearActionPerformed

     private void clearAllFields() {                                         
        // TODO add your handling code here:
       
        txtVno.setText(" ");
             txtVtype.setText(" ");
            txtDriid.setText(" ");
            txtDriname.setText(" ");
            txtDricont.setText(" ");
            cmbPro1.setSelectedItem(" ");
            cmbPro2.setSelectedItem(" ");
            cmbPro3.setSelectedItem(" ");
            txtRfrom.setText(" ");
            txtRto.setText(" ");
            txtTotdis.setText(" ");
            txtDname.setText(" ");
            txtDcont.setText(" ");
        
    }             
    
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
          con=ConnectDB.condb();
        try
        {
            pst=(OraclePreparedStatement)con.prepareStatement("insert into TRANSPORT values(?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
                      
             pst.setInt(1, Integer.parseInt(txtVid.getText()+""));
             pst.setString(2,txtVno.getText()+"");
             pst.setString(3,txtVtype.getText()+"");
            pst.setInt(4, Integer.parseInt(txtDriid.getText()+""));
            pst.setString(5,txtDriname.getText()+"");
            pst.setString(6,txtDricont.getText()+"");
            pst.setString(7,cmbPro1.getSelectedItem()+"");
            pst.setString(8,cmbPro2.getSelectedItem()+"");
            pst.setString(9,cmbPro3.getSelectedItem()+"");
            pst.setString(10,txtRfrom.getText()+"");
            pst.setString(11,txtRto.getText()+"");
            pst.setString(12,txtTotdis.getText()+"");
            pst.setString(13,txtDname.getText()+"");
            pst.setString(14,txtDcont.getText()+"");
            pst.executeUpdate();                 
                    
            JOptionPane.showMessageDialog(this,"Saved...");
            pst.close();   
            clearAllFields();
            getTransportId();
           
        }

        catch(Exception e)
        {}
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtVidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVidKeyReleased
        // TODO add your handling code here:
        
        con=ConnectDB.condb();
        try
        {
            smt=(OracleStatement)con.createStatement();
            rs=(OracleResultSet)smt.executeQuery("select * from TRANSPORT where V_ID="+ (txtVid.getText()));
            while(rs.next())
            {
                
            txtVno.setText(" "+rs.getString(2));
             txtVtype.setText(" "+rs.getString(3));
            txtDriid.setText(" "+rs.getString(4));
            txtDriname.setText(" "+rs.getString(5));
            txtDricont.setText(" "+rs.getString(6));
            cmbPro1.setSelectedItem(" "+rs.getString(7));
            cmbPro2.setSelectedItem(" "+rs.getString(8));
            cmbPro3.setSelectedItem(" "+rs.getString(9));
            txtRfrom.setText(" "+rs.getString(10));
            txtRto.setText(" "+rs.getString(11));
            txtTotdis.setText(" "+rs.getString(12));
            txtDname.setText(" "+rs.getString(13));
            txtDcont.setText(" "+rs.getString(14));
            }
           

        }
        catch(Exception e)
        {
        }
        
    }//GEN-LAST:event_txtVidKeyReleased

    
    private void getTransportId() {                                        
        // TODO add your handling code here:
        con=ConnectDB.condb();
        try
        {
            smt=(OracleStatement)con.createStatement();
            rs=(OracleResultSet)smt.executeQuery("select count(*) from TRANSPORT");
            while(rs.next()){
                txtVid.setText((Integer.parseInt(rs.getString(1))+1 )+"");
                System.out.println("rs.getString(1)  :"+rs.getString(1));
            }
        }
        catch(Exception e)
        {}
        
    } 
    
    
    private void txtVnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVnoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVnoKeyReleased

    private void txtVidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVidKeyPressed
        // TODO add your handling code here:
        
        int key=evt.getKeyCode();
         if ((key>=evt.VK_0&&key<=evt.VK_9)||(key>=evt.VK_NUMPAD0&&key<=evt.VK_NUMPAD9)||key==KeyEvent.VK_BACK_SPACE)
         {
            txtVid.setEditable(true);
            txtVid.setBackground(Color.white);
             
            
         }
         else
         {    
            txtVid.setEditable(false);
        txtVid.setBackground(Color.red);
         
        }
        
        
        
    }//GEN-LAST:event_txtVidKeyPressed

    private void txtDricontKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDricontKeyPressed

int key=evt.getKeyCode();
         if ((key>=evt.VK_0&&key<=evt.VK_9)||(key>=evt.VK_NUMPAD0&&key<=evt.VK_NUMPAD9)||key==KeyEvent.VK_BACK_SPACE)
         {
            txtDricont.setEditable(true);
            txtDricont.setBackground(Color.white);
             
            
         }
         else
         {    
            txtDricont.setEditable(false);
        txtDricont.setBackground(Color.red);
         
        }
        

        // TODO add your handling code here:
    }//GEN-LAST:event_txtDricontKeyPressed

    private void txtDcontKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDcontKeyPressed


        int key=evt.getKeyCode();
         if ((key>=evt.VK_0&&key<=evt.VK_9)||(key>=evt.VK_NUMPAD0&&key<=evt.VK_NUMPAD9)||key==KeyEvent.VK_BACK_SPACE)
         {
            txtDcont.setEditable(true);
            txtDcont.setBackground(Color.white);
             
            
         }
         else
         {    
            txtDcont.setEditable(false);
        txtDcont.setBackground(Color.red);
         
        }
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDcontKeyPressed

    private void txtDriidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDriidKeyPressed

int key=evt.getKeyCode();
         if ((key>=evt.VK_0&&key<=evt.VK_9)||(key>=evt.VK_NUMPAD0&&key<=evt.VK_NUMPAD9)||key==KeyEvent.VK_BACK_SPACE)
         {
            txtDriid.setEditable(true);
            txtDriid.setBackground(Color.white);
             
            
         }
         else
         {    
            txtDriid.setEditable(false);
        txtDriid.setBackground(Color.red);
         
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDriidKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTransport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTransport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTransport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTransport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTransport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbPro1;
    private javax.swing.JComboBox<String> cmbPro2;
    private javax.swing.JComboBox<String> cmbPro3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblTime;
    private javax.swing.JTextField txtDcont;
    private javax.swing.JTextField txtDname;
    private javax.swing.JTextField txtDricont;
    private javax.swing.JTextField txtDriid;
    private javax.swing.JTextField txtDriname;
    private javax.swing.JTextField txtRfrom;
    private javax.swing.JTextField txtRto;
    private javax.swing.JTextField txtTotdis;
    private javax.swing.JTextField txtVid;
    private javax.swing.JTextField txtVno;
    private javax.swing.JTextField txtVtype;
    // End of variables declaration//GEN-END:variables

}